### ISSUE TITLE
Compliance-masonry causes "Segmentation fault: 11" on OSX 10.13.5

### ISSUE THREAD

**Issue by gregelin** [opencontrol/compliance-masonry#316]
Any attempt to run `compliance-masonry` on  OSX 10.13.5 throws "Segmentation fault: 11" as in:

```
Gregs-MacBook-Pro:Downloads greg$ compliance-masonry
Segmentation fault: 11
```

Still getting Segmentation fault after uninstalling and reinstalling both Go and compliance-masonry.

```
Gregs-MacBook-Pro:Downloads greg$ go version
go version go1.10.3 darwin/amd64

Gregs-MacBook-Pro:~ greg$ which go
/usr/local/bin/go
Gregs-MacBook-Pro:~ greg$ which compliance-masonry
/usr/local/bin/compliance-masonry
```

Perhaps related, I seem unable to set `GOPATH` in my `~/.bash_profile`

```
$ # from my ~/.bash_profile

# Path for $GOPATH
# Created directory ~/.gocode for $GOPATH
export GOPATH=$HOME/.gocode
export PATH=${GOPATH//://bin:}/bin:$PATH
export GOPATH2=something

Gregs-MacBook-Pro:~ greg$ $HOME
-bash: /Users/greg: Is a directory
Gregs-MacBook-Pro:~ greg$ $GOPATH2
-bash: something: command not found
Gregs-MacBook-Pro:~ greg$ $GOPATH
Gregs-MacBook-Pro:~ greg$ 
```

**Comment by gregelin** [comment]
@redhatrises 

Here's what I did. Repeated just now.

```
Gregs-MacBook-Pro:Downloads greg$ cd ~/Downloads
Gregs-MacBook-Pro:Downloads greg$ curl -L https://github.com/opencontrol/compliance-masonry/releases/download/v1.1.2/compliance-masonry_1.1.2_darwin_amd64.zip -o compliance-masonry.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   631    0   631    0     0    773      0 --:--:-- --:--:-- --:--:--   772
100 3373k  100 3373k    0     0   452k      0  0:00:07  0:00:07 --:--:--  649k
Gregs-MacBook-Pro:Downloads greg$ which compliance-masonry
/usr/local/bin/compliance-masonry
Gregs-MacBook-Pro:Downloads greg$ rm -Rf /usr/local/bin/compliance-masonry 
Gregs-MacBook-Pro:Downloads greg$ which compliance-masonry
Gregs-MacBook-Pro:Downloads greg$ 
Gregs-MacBook-Pro:Downloads greg$ 
Gregs-MacBook-Pro:Downloads greg$ unzip compliance-masonry.zip
Archive:  compliance-masonry.zip
  inflating: compliance-masonry_1.1.2_darwin_amd64/compliance-masonry  
  inflating: compliance-masonry_1.1.2_darwin_amd64/README.md  
  inflating: compliance-masonry_1.1.2_darwin_amd64/LICENSE.md  
Gregs-MacBook-Pro:Downloads greg$ cp compliance-masonry_1.1.2_darwin_amd64/compliance-masonry /usr/local/bin
Gregs-MacBook-Pro:Downloads greg$ compliance-masonry
Segmentation fault: 11
```

**Comment by redhatrises** [comment]
@gregelin could you try it with the latest release? 

```curl -L https://github.com/opencontrol/compliance-masonry/releases/download/v1.1.4/compliance-masonry_1.1.4_darwin_amd64.tar.gz -o compliance-masonry.tar.gz```

This could be a function of an older version of go.

**Comment by gregelin** [comment]
@redhatrises Thanks. That seemed to help. Segmentation fault fixed. New version of compliance-masonry works. Had to copy `compliance-masonry` and `masonry` to `/usr/local/bin` before a command worked, but still getting a bit stuck.

```
Gregs-MacBook-Pro:Downloads greg$ rm -Rf /usr/local/bin/compliance-masonry 
Gregs-MacBook-Pro:Downloads greg$ rm compliance-masonry.zip
Gregs-MacBook-Pro:Downloads greg$ rm -Rf compliance-masonry_1.1.2_darwin_amd64
Gregs-MacBook-Pro:Downloads greg$ curl -L https://github.com/opencontrol/compliance-masonry/releases/download/v1.1.4/compliance-masonry_1.1.4_darwin_amd64.tar.gz -o compliance-masonry.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   634    0   634    0     0   1612      0 --:--:-- --:--:-- --:--:--  1613
100 3245k  100 3245k    0     0  1023k      0  0:00:03  0:00:03 --:--:-- 1241k

Gregs-MacBook-Pro:Downloads greg$ cp compliance-masonry /usr/local/bin/
Gregs-MacBook-Pro:Downloads greg$ which compliance-masonry
/usr/local/bin/compliance-masonry
Usage: masonry [OPTIONS] COMMAND [ARGS]...

Options:
  -v, --verbose  Toggle logging
  --help         Show this message and exit.

Commands:
  certs      Create certification yamls
  docs       Create certification documentation
  init       Initalize a new control masonry project
  inventory  Creates an inventory for a specific...
  new        Command for generating new yaml files

Gregs-MacBook-Pro:myproject greg$ compliance-masonry init
New Project: `data`
Gregs-MacBook-Pro:myproject greg$ ls
data			opencontrol.yaml	opencontrols

Gregs-MacBook-Pro:myproject greg$ cp ~/Downloads/masonry /usr/local/bin/masonry 
```

So that's progress.

Now I try to run...

```
Gregs-MacBook-Pro:myproject greg$ compliance-masonry get
An error occurred: [Error: Repo initialization failed Repo: github.com/18F/LATO Revision: master Dir: /var/folders/rk/cn5lpv2s2g1cwplxcrdxzj1r0000gn/T/opencontrol-resources560332404/certifications/LATO Error Details: Cannot detect VCS]
```

I have not YET tried to debug this. Have to run to a meeting.

my `opencontrol.yaml`

```
schema_version: "1.0.0" # 1.0.0 is the current opencontrol.yaml schema version
name: Project_Name # Name of the project
metadata:
  description: "A description of the system"
  maintainers:
    - maintainer_email@email.com
components: # A list of paths to components written in the opencontrol format for more information view: https://github.com/opencontrol/schemas
#  - ./component-1
certifications: # An optional list of certifications for more information visit: https://github.com/opencontrol/schemas
#  - ./cert-1.yaml
   - ./data/certifications/FedRAMP-low.yaml
standards: # An optional list of standards for more information visit: https://github.com/opencontrol/schemas
  - ./data/standards/NIST-800-53.yaml 
dependencies:
  certifications: # An optional list of certifications stored remotely
    - url: github.com/18F/LATO
      revision: master
  systems:  # An optional list of repos that contain an opencontrol.yaml stored remotely
    - url: github.com/18F/cg-compliance
      revision: master
  standards:   # An optional list of remote repos containing standards info that contain an opencontrol.yaml
    - url: github.com/18F/NIST-800-53
      revision: master
```
