### ISSUE TITLE
consider leveraging dependabot

### ISSUE THREAD

**Issue by aegershman** [opencontrol/compliance-masonry#358]
see: I believe this would be contingent on https://github.com/opencontrol/compliance-masonry/pull/355

In order to evaluate any outdated go dependencies & generally set up infrastructure to keep compliance-masonry up-to-date, consider leveraging [github-integrated dependabot](https://dependabot.com/go/). 

---

Posting a snippet of what the `dependabot.yml` file content **could** look like. Since it's so small I figure I'd put it within this same tracking issue to keep it simple (I didn't want to assume a PR would even be wanted in this case):

```yml
# .github/dependabot.yml
---
version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
```

... I think, at least. I haven't tried it out yet. I could try it out on a temporary hard fork of this repo. I'll update this issue if I get to doing that sometime this week and seeing if it works as expected 👍 

Thanks for folks' time and consideration
