### ISSUE TITLE
Current Yaml format of documentation. 

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#6]
Since data is more closely organized as the `Certification Justifications`. The first step will be to covert data from the SSP Controls Matrix to the certification justification format. 

## My Cloud.gov/AWS/18F Controls
Without being combined with the standards and certifications yamls the control yamls can be use to generate readable documentation w/ gitbook, etc...

```yaml
## Cloudgov.yaml
CF_UAA:
  name: Cloud Foundry User Authentication and Authorization (UAA)
  references:
    - name: UAA design doc
      url: https://asdfasdf
    - name: Some other doc
      url: https://boobarbazbat
  governors:
    - name: UAA configuration
      url: https://pathtogitrepohead
    - name: Live test results
      url: https://dashboardwithupdatedtestresults
  satisfies:
    - standard:
        NIST-800-53:
           - element: AC-2-a
             narrative: Description of now CF_UUA meets point control X sub mod. a
```

## Standards Documentation
```yaml
# nist-800-53.yaml
standards:
  C-2:
    name: User Access
    description: There is an affordance for managing access by...

# PCI.yaml
standards:
  Regulation-6:
    name: User Access PCI
    description: There is an affordance for managing access by...
```

## Certifications
Empty yaml for creating certification documentation. Serve as a template for combining controls and standards yamls.
```yaml
# Fisma.yaml
standards:
  nist-800-53:
    C-2:
    C-3:
  PCI:
    6:
```

## Certification Justifications
Centralized yaml for a specific certification, can be used to render matrix.csv, gitbook.md, ssp.docx... This is were we will be able to see if any pieces are missing.
```yaml
# FISMA.yaml
AC-2:
  a:
  - title: Title of control requirement justifications
    justifications:
    - id: CF_UAA
      name: Cloud Foundry User Authentication and Authorization (UAA)
      narrative: Description of now CF_UUA meets point control X sub mod. a
      references:
        - name: UAA design doc
          url: https://asdfasdf
        - name: Some other doc
          url: https://boobarbazbat
      governors:
        - name: UAA configuration
          url: https://pathtogitrepohead
        - name: Live test results
          url: https://dashboardwithupdatedtestresults
```
