### ISSUE TITLE
Hierarchy of Components

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#8]
Under the current structure, controls are mapped to components of systems. For example, in the yaml below the `UAA`, a component of `Cloud Foundry` satisfies the `AC-2` control.
```yaml
name: User Account and Authentication (UAA) Server
references:
- reference_name: User Account and Authentication (UAA) Server
  reference_url: http://docs.pivotal.io/pivotalcf/concepts/architecture/uaa.html
governors:
- governor_name: Cloud Foundry Roles
  governor_url: https://cf-p1-docs-prod.cfapps.io/pivotalcf/concepts/roles.html
satisfies:
  AC-2: Cloud Foundry accounts are managed through the User Account and Authentication
    (UAA) Server.
```
However, sometimes components like the `UAA` depend on sub-components like `CA Siteminder` to satisfy controls. Am I explaining this correctly @joshuamckenty?

Any ideas on how to represent this? We could have folders that contain sub-component yamls

```
+-- CloudFoundry
|   +-- UAA.yaml
|   +-- UAA
    | +-- CA_Siteminder.yaml
```
