### ISSUE TITLE
Changing Schema 

### ISSUE THREAD

**Issue by geramirez** [opencontrol/compliance-masonry#85]
Considering schema change to: 

### AWS/EC2.yaml
```yaml
name: Amazon Elastic Compute Cloud # Name of the component
documentation_complete: false # Manual check if the documentation is complete (for gap analysis)
references:
  - name: Reference  # Name of the reference ie. EC2 website
    url: Refernce URL  # Url of the reference
    type: URL # type of reference (will affect how it's rendered in the documentation)
verifications:
  EC2_Verification_1: # ID of verification
    name: EC2 Verification 1  # Name of verification
    url: Verification 1 URL #  URL of the verification
    type: URL # type of reference (will affect how it's rendered in the documentation)
  EC2_Verification_2:
    name: EC2 Governor 2
    url: Verification 2 URL
    type: Image
satisfies:
  NIST-800-53:
    CM-2:
      narrative: Justification in narrative form # Justification text
      implementation_status: partial # Manual status of implementation (for gap analysis)
      references:
        - verification: EC2_Verification_1 # The specific verification ID that the reference links, no component or system is needed for internal references
        - system: CloudFoundry  # System name of the verification (can link to other systems / components)
          component: UAA  # System name of the verification (can link to other systems / components)
          verification: UAA_Verification_1 # The specific verification ID that the reference links to
```

### CloudFoundry/UAA.yaml
```yaml
name: User Account and Authentication (UAA) Server
documentation_complete: false
references:
  - name: Reference
    url: Refernce URL
    type: URL
verifications:
  UAA_Verification_1:
    name: UAA Verification 1
    url: Verification 1 URL
    type: URL
  UAA_Verification_2:
    name: UAA Verification 2
    url: Verification 2 URL
    type: Image
satisfies:
  NIST-800-53:
    AC-2:
      narrative: Justification in narrative form
      implementation_status: complete
```

### exports/certifications/LATO.yaml
A certification yaml
```yaml
components: # An object for storing components this information will be rendered in a appendix.
  AWS:
    EC2:
      documentation_complete: false
      name: Amazon Elastic Compute Cloud
      references:
      - name: Reference
        type: URL
        url: Refernce URL
      verifications:
        EC2_Verification_1:
          name: EC2 Verification 1
          type: URL
          url: Verification 1 URL
        EC2_Verification_2:
          name: EC2 Governor 2
          type: Image
          url: Verification 2 URL
  CloudFoundry:
    UAA:
      documentation_complete: false
      name: User Account and Authentication (UAA) Server
      references:
      - name: Reference
        type: URL
        url: Refernce URL
      verifications:
        UAA_Verification_1:
          name: UAA Verification 1
          type: URL
          url: Verification 1 URL
        UAA_Verification_2:
          name: UAA Verification 2
          type: Image
          url: Verification 2 URL
name: LATO
standards:
  NIST-800-53:
    AC-2:
      justifications:
      - component: UAA
        implementation_status: complete
        narrative: Justification in narrative form
        references: null
        system: CloudFoundry
      meta:
        name: Account Management
    AC-6:
      meta:
        name: Least Privilege
    CM-2:
      justifications:
      - component: EC2
        implementation_status: partial
        narrative: Justification in narrative form
        references: # verifications that don't have a a system and components are given thier parent's
        - component: EC2
          system: AWS
          verification: EC2_Verification_1
        - component: UAA
          system: CloudFoundry
          verification: UAA_Verification_1
        system: AWS
      meta:
        name: Baseline Configuration
```
# Potential Markdown output
--------------
# components.md
--------------
##### References
- [Reference](Reference URL)

#### Verifications
- [EC2 Verification 1](Verification URL)
- [EC2 Verification 2](Verification URL)

### References
- [Reference](Reference URL)

### Verifications
- [UAA Verification 1](Verification URL)
- [UAA Verification 2](Verification URL)

------------------
# AC-2.md
---------------------
#### CloudFoundry - UAA
Justification in narrative form

------------------
# CM-2.md
---------------------

#### AWS - Amazon Elastic Compute Cloud
Justification in narrative form

- [EC2 Verification 1](Verification 1 URL)
- [UAA Verification 1](Verification 1 URL)

**Comment by gregelin** [comment]
@geramirez The term "Governor" is a bit unclear. What does it mean in this context? Do we have a glossary.

**Comment by geramirez** [comment]
@gregelin originally we defined a governor as a `(link to inspect how [a component is] actually configured to run, live... config files, live tests, kanban board, role roster, etc)` Basically, it's an artifact that proves that a control is implemented. When we start creating automated tests we'll hook into the governors. 

However, if the name is unclear we could change it to something more intuitive. Maybe just artifact perhaps? Thoughts?

**Comment by Gergues** [comment]
In some systems that would be name "Qualifier" (some FDA documents)
"Qualifier" : Rule(x) is satisfied by Implementation(Xn).
Or : Xn is a list of implementations that satisfied rule x.

The name artifact will require a link or item of sort ,but that can be implicit with the nature of the system. [ RBACS implies users, groups, policies etc. so the number of artifacts may not match the number of rules and in many case will be one to many]

In any case the name is irrelevant as we know what is means.

**Comment by openprivacy** [comment]
Would "conform to server baseline" be a Rule satisfied by running e.g, OpenSCAP with the appropriate profile, or would each separate test in the profile have its own rule? The latter is better for granularity and control, but of course duplicates work of other projects.

**Comment by gregelin** [comment]
@geramirez I think "governor" is an OK term. Here are some other possibilities:
- controllers
- services
- endpoints
- configurations
- inspectors
- providers
- interfaces
- accessors

**Comment by gregelin** [comment]
Two thoughts on the general structure:

1. Can we the example with more than one component? My concern is if this structure is in a file by itself or part of a larger yaml file with multiple components. If the latter, "component" and "system" and "documentation_complete" are all on the same level.
2. I can't figure out how I feel about using the "AC-2" as both key and identifier. It definitely affects how you write a parser.  I think it is important for Compliance-Masonry to have a consistent approach to whether or not we always have a key and a value vs. key that is also a value position dependent. I think consistency is more important than the choice, and I think providing example code is important.

**Comment by gregelin** [comment]
@mogul @geramirez Can we add a couple of actual examples in this thread of target artifacts?  

- The term "Governor" suggests and actor/agent/something that does something. 
- "Configuration" suggests settings/something that can be adjusted. 
- "Verification" suggests a result, an artifact/evidence/assessment/result.

**Comment by geramirez** [comment]
I like verification, it seems to convey a more precise meaning than configuration. Let's try it
.

**Comment by joshuamckenty** [comment]
When Diego and I were chatting about this in Berlin, I noted that the “human-readable” aspects of the configuration detail are likely to be *different* from the “machine-validated” tests that can be run to prove this configuration. So my hunch is that we’ll need to separate validated_by from reference.

**Comment by dlapiduz** [comment]
`verification` and `validated_by` both sound good... not sure where the term `governor` came from but it definitely has its issues.

The more human readable that we make the yaml the better...

**Comment by geramirez** [comment]
@joshuamckenty do you mind going into more detail about this. I think you bring up a really important distinction.
> So my hunch is that we’ll need to separate validated_by from reference

Right now we have `references`, which we are using as links to information about a component. These `references` are different than `validations`, which essentially prove that components are satisfying the control requirements. 

Are you saying that there should be two different types of `validations`? such as:
1. Validations that point to human-readable system/component configurations 
2. Validations that point to machine-validated tests of system/components

... or that we should be using
1.  `references` as pointers to human-readable system/component configurations, and
2. `validations` as pointers to machine-validated tests of system/components?

**Comment by gregelin** [comment]
@geramirez I agree with @joshuamckenty that there will be controls that `human_validated` and `machine_validated`. In fact, a `human_validated` control in one organization may be `machine_validated` in another.

I think `references` are citations. A `reference` refers to another document/artifact. Government frequently incorporate an external source by reference. You see this all the time in contracts and also in polices. So, I _think_ it is best to align with that trend. I write, "I _think_" because, incorporation by reference in government contracts and policies also gets really annoying where one is chasing down reference after reference to establish proper interpretation. We've all probably had moments of exasperation looking at full page of clauses incorporated by reference.

My feeling is a `reference` definitely can be used to "link to information about a component." 

Maybe the question is if a `validation` is a type of reference that links to direct evidence proving a control implemented (e.g. `human_validated` and/or `machine_validated`), or is `validation` a description of evidence that may include a `reference` specific evidence?

**Comment by geramirez** [comment]
I like the former. How about adding something like this to the schema:

```
verifications:
  EC2_Verification_1: # ID of verification
    name: EC2 Verification 1  # Name of verification
    url: Verification 1 URL #  URL of the verification
    type: URL # type of reference (will affect how it's rendered in the documentation)
    validated_by: Validator X # Name or ID of validator human or machine 
```
